### ISSUE TITLE
screenshot for full blown UI somewhere?

### ISSUE THREAD

**Issue by laoshaw** [lc-soft/LCUI#128]
﻿do you have some screenshot with a full blown UI made by LCUI? the tutorial ones look really bare bone.

**Comment by lc-soft** [comment]
Do you mean that you need some screenshots of the application that contains full UI features, instead of demo screenshots?

**Comment by laoshaw** [comment]
exactly, for UI projects some full-potential screenshots will always be helpful and hopefully, attractive.

**Comment by lc-soft** [comment]
I only used LCUI to develop [PunchAndKick](https://github.com/lc-soft/PunchAndKick) and [LC's Finder](https://github.com/lc-soft/LC-Finder), But they use an older version of LCUI, does not have the reference value.

You can tell me what you want to see, I will consider implementing it on other demo.

Or, you can wait for the [LCUI.css](https://github.com/lc-ui/lcui.css) 1.0 version to experience the effects of the interface

**Comment by laoshaw** [comment]
will just wait for 1.0 release then. thanks.
