### ISSUE TITLE
Is Development possible on Mac?

### ISSUE THREAD

**Issue by soorajvnair** [lc-soft/LCUI#129]
First of all, Great work on the Library, Well done. :)

In the documentation pages, i can see the instructions to setup the dev environment on both Linux and Windows, was wondering if this was possible on Mac as well? And whether you would be adding the instructions for Mac soon?

**Comment by lc-soft** [comment]
I do not have Mac.

Adding other platform support is not a major task now, Because there are other problems that I need to solve.

**Comment by soorajvnair** [comment]
Thanks @lc-soft I can take a stab at it.

**Comment by lc-soft** [comment]
If you want to help, you can provide some reference documents, for example:

- http://hg.libsdl.org/SDL/file/7b4cee950f96/src/video/x11/SDL_x11framebuffer.c#l56
- https://tronche.com/gui/x/xlib/
- http://www.geeks3d.com/20120102/programming-tutorial-simple-x11-x-window-code-sample-for-linux-and-mac-os-x/
