### ISSUE TITLE
[layout] widget_layout.h is missing

### ISSUE THREAD

**Issue by odknt** [lc-soft/LCUI#132]
I got an error message when build.

```
/usr/include/LCUI/gui/widget.h:47:10: fatal error: LCUI/gui/widget_layout.h: No such file or directory
 #include <LCUI/gui/widget_layout.h>
```

**Reproduction Steps:**

1. `./autogen.sh`
2. `./configure --prefix=/usr`
3. `make && make install`
4. Build the code below.

```c
#include <LCUI_Build.h>
#include <LCUI/LCUI.h>
#include <LCUI/gui/widget.h>
#include <LCUI/gui/widget/textview.h>

int
main (int argc, char *argv[])
{
  (void)argc;
  (void)argv;

  LCUI_Widget root, text;

  LCUI_Init ();
  root = LCUIWidget_GetRoot ();
  text = LCUIWidget_New ("textview");
  TextView_SetText (text, "Hello World!");
  Widget_Append (root, text);

  return LCUI_Main ();
}
```

**LCUI version:** v1.0-beta
**OS and version:** Linux
**Build tools:** gcc 7.3.0

**Comment by lc-soft** [comment]
widget_layout.h is missing in [include/LCUI/gui/Makefile.am](https://github.com/lc-soft/LCUI/blob/develop/include/LCUI/gui/Makefile.am), You can add it. 

I also welcome you submit a Pull Pequest.
