### ISSUE TITLE
High idle CPU usage

### ISSUE THREAD

**Issue by coderobe** [lc-soft/LCUI#134]
The LCUI examples `helloworld` and `test` have an extremely high idle cpu usage.  
They seem to max out 4 of my 8 cores to 100% utilization on my Intel i7-4710HQ, which corresponds to the 4 worker threads used by `helloworld`.
This should probably not be the case, considering `helloworld` is doing basically nothing without user interaction.

**Reproduction Steps:**

1. Build current `develop` branch
2. Build examples in `test/`
3. Run the built `helloworld` or `test`

**LCUI version:** branch `develop` commit `d65de98bee17e0eeaa9f339c81ffcdadc4bed60f`
**OS and version:** Linux 4.15.1
**Build tools:** gcc (GCC) 7.3.0
**Libraries (taken from LCUI_LIBS in the generated Makefile):**
- libxml2 2.9.7
- freetype 2.9
- libx11 1.6.5
- libpng 1.6.34
- zlib 1.2.11
- libjpeg-turbo 1.5.3

**Comment by coderobe** [comment]
The source of the issue seems to be here: https://github.com/lc-soft/LCUI/blob/d65de98bee17e0eeaa9f339c81ffcdadc4bed60f/src/worker.c#L107

It doesn't seem like this is waiting as expected. Using `sleep()` from `<unistd.h>` as a replacement to this, like so: `sleep(1);`, lowers the CPU usage to almost nothing.

Here's a patch that works around the issue the way i explain above:
```diff
--- src/worker.c			2018-02-09 01:32:37.992205667 +0100
+++ work-around-idle-cpu-usage.patch	2018-02-09 02:05:25.341165522 +0100
@@ -41,6 +41,7 @@
 
 #include <errno.h>
 #include <stdlib.h>
+#include <unistd.h>
 #include <LCUI_Build.h>
 #include <LCUI/LCUI.h>
 #include <LCUI/thread.h>
@@ -104,6 +105,7 @@
 			continue;
 		}
 		if( worker->active ) {
+			sleep(1);
 			LCUICond_Wait( &worker->cond, &worker->mutex );
 		}
 	}
```
Please note that that is most definitely not an acceptable fix but rather a hot-patch to temporarily work around the issue.

**Comment by lc-soft** [comment]
found.

![image](https://user-images.githubusercontent.com/1730073/36009934-b0e8ef32-0d89-11e8-95a5-3fe65e0b54e2.png)

**Comment by lc-soft** [comment]
Yes, the LCUICond_Wait() did not wait. I will write a test case to test it.

``` text
[worker] worker 2613421824 is stopping...
[worker] worker 2613421824 has run 33202211 tasks
[worker] worker 2613421824 has stopped
[worker] worker 2605029120 is stopping...
[worker] worker 2605029120 has run 35400220 tasks
[worker] worker 2605029120 has stopped
[worker] worker 2596636416 is stopping...
[worker] worker 2596636416 has run 34350696 tasks
[worker] worker 2596636416 has stopped
[worker] worker 2588243712 is stopping...
[worker] worker 2588243712 has run 34531617 tasks
[worker] worker 2588243712 has stopped
```
