### ISSUE TITLE
Error when building: "‘struct dirent’ has no member named ‘d_reclen’"

### ISSUE THREAD

**Issue by ForsakenHarmony** [lc-soft/LCUI#141]
```
dirent.c:147:8: error: ‘struct dirent’ has no member named ‘d_reclen’
       d->d_reclen + 1, ENCODING_UTF8 );
        ^~
```

**Reproduction Steps:**

1. follow linux instructions in cygwin
2. error when executing `make`

**LCUI version:** latest master
**OS and version:** Win10
**Build tools:** cygwin make

**Comment by ForsakenHarmony** [comment]
also found this which doesn't have the field
http://pubs.opengroup.org/onlinepubs/7908799/xsh/dirent.h.html

**Comment by lc-soft** [comment]
In Windows, you need use VisualStudio to compile it.

I have not tried using ·cygwin make·， maybe you can try to change config.h file, add macro define:

``` c
#define LCUI_BUILD_IN_WIN32
#define _WIN32
```

**Comment by ForsakenHarmony** [comment]
I'm trying to do it without visual studio because I want to make rust bindings

**Comment by lc-soft** [comment]
Any other questions need my help?

**Comment by lc-soft** [comment]
``` diff
-	LCUI_DecodeString( dir->entry.name, d->d_name, 
-			   d->d_reclen + 1, ENCODING_UTF8 );
+	LCUI_DecodeString( dir->entry.name, d->d_name, 0, ENCODING_UTF8 );
```
