### ISSUE TITLE
OSX support?

### ISSUE THREAD

**Issue by sam0x17** [lc-soft/LCUI#142]
Not sure if this is currently planned, but if this can hit all 3 major OSes then my company and several of my consulting clients would be able to switch from Electron to this.

**Comment by lc-soft** [comment]
> OSX support? Not sure if this is currently planned

Not support OSX. there is no plan for a short time, 

> but if this can hit all 3 major OSes then my company and several of my consulting clients would be able to switch from Electron to this.

I suggest you continue to use Electron, it is more powerful, allow to use many JavaScript frameworks to build user interfaces with Electron, and it can achieve many effects for the user interface. But if you use LCUI, you will encounter the following problems:

- Sometimes the application will crash.
- Can not use animation.
- Can not play video and sound.
- Can not use table to display data.
- And more.

This project needs a lot of time to improve, do not try to use it in important products.

**Comment by lieff** [comment]
@sam0x17 Consider using https://github.com/vurtun/nuklear and https://github.com/ocornut/imgui for all 3 major OS.
