### ISSUE TITLE
Interest in porting to rust?

### ISSUE THREAD

**Issue by ForsakenHarmony** [lc-soft/LCUI#148]
Just asking if you (the author) would be interested in porting this project to rust, would make compiling cross platform a lot easier and still allows C bindings 

I'll try to write rust bindings for this no matter what

**Comment by lieff** [comment]
I think bindings is enough, no need for double work.

**Comment by ForsakenHarmony** [comment]
the problem is make which is not cross platform

**Comment by lc-soft** [comment]
Not interested.

**Comment by ForsakenHarmony** [comment]
alright
