### ISSUE TITLE
关于输入法的改进的疑问

### ISSUE THREAD

**Issue by sw5cc** [lc-soft/LCUI#149]
你好，LCUI 的代码写的真好真美观。
我之前在做LCUI 的输入法改进，
LCUI 的事件参数传递是单向的，但是输入法的那几个事件要求把数据传回。
```C++
WM_IME_REQUEST 			// Sent to an application to provide commands and request information.
    IMR_CANDIDATEWINDOW 
    IMR_COMPOSITIONFONT 
    IMR_COMPOSITIONWINDOW 
    IMR_CONFIRMRECONVERTSTRING 
    IMR_DOCUMENTFEED 
    IMR_QUERYCHARPOSITION 
    IMR_RECONVERTSTRING 
```
比如说 [IMR_QUERYCHARPOSITION](https://msdn.microsoft.com/en-us/library/windows/desktop/dd318634(v=vs.85).aspx)  这个，如果自绘输入法的COMPOSITION WINDOW，那么需要把位置信息写回结构体。

有什么好的办法吗？

**Comment by lc-soft** [comment]
你的问题是如何主动发送 WM 消息？如何获取当前输入框的光标坐标？

**Comment by sw5cc** [comment]
不需要主动发送WM消息，但要把光标坐标写回 WM_IME_REQUEST 消息的 lparam 里。lparam 是一个这个结构 [IMECHARPOSITION ](https://msdn.microsoft.com/en-us/library/windows/desktop/dd318162(v=vs.85).aspx)

**Comment by lc-soft** [comment]
那可以调用 LCUI_BindSysEvent()，绑定 WM_IME_REQUEST 消息处理器，参考：https://github.com/lc-soft/LCUI/blob/bf9d3277f5bd46b95b0568bc00784af2274063e4/src/platform/windows/windows_mouse.c#L149

**Comment by lc-soft** [comment]
关于光标坐标的获取问题，你需要：

1. 在 LCUIWidget_SetFocus() 后面添加 LCUIWidget_GetFocus() 函数用于获取当前焦点部件
  https://github.com/lc-soft/LCUI/blob/2064b10f96e9a08a660f627b4cb898b3bf9c15fd/src/gui/widget_event.c#L718
1. 在 gui/widget/textedit.c 里添加 TextEdit_GetCaretPosition() 获取光标相对于输入框的坐标

**Comment by sw5cc** [comment]
对的，WM_IME_REQUEST 用 LCUI_BindSysEvent 绑定应该就可以了，那我去研究一下
