### ISSUE TITLE
linux FRAMEBUFFER 释放BUG

### ISSUE THREAD

**Issue by zhouxl6** [lc-soft/LCUI#157]
在 src/platform/linux/linux.display.c 代码 LCUI_DestroyLinuxDisplayDriver 函数中
关于LCUI_DestroyLinuxFBDisplayDriver调用前的宏定义是否应该 LCUI_VIDEO_DRIVER_FRAMEBUFFER 而不是 LCUI_VIDEO_DRIVER_X11 ?

即：
#ifdef LCUI_VIDEO_DRIVER_X11
	case X11:
		LCUI_DestroyLinuxX11DisplayDriver( driver );
		break;
#endif
#ifdef LCUI_VIDEO_DRIVER_FRAMEBUFFER     //现在源码中这里是 LCUI_VIDEO_DRIVER_X11
	case FRAMEBUFFER:
		LCUI_DestroyLinuxFBDisplayDriver( driver );
		break;
#endif

**Comment by lc-soft** [comment]
You can create a Pull Request.
