### ISSUE TITLE
Cursor bugs on windows

### ISSUE THREAD

**Issue by dossalab** [lc-soft/LCUI#161]
I've recently updated from LCUI beta 2 to beta 3. (VS 2017):
![cursor](https://user-images.githubusercontent.com/20026104/46599366-e0a98280-caef-11e8-99af-911870a418b8.gif)
Looks like LCUI is attaching picture to the cursor in LCUI_InitCursor():
```
void LCUI_InitCursor(void)
{
	LCUI_Graph pic;
	Graph_Init(&pic);
	Graph_Init(&cursor.graph);
	/* 载入自带的游标的图形数据 */
	LCUICursor_LoadDefualtGraph(&pic);
	cursor.new_pos.x = LCUIDisplay_GetWidth() / 2;
	cursor.new_pos.y = LCUIDisplay_GetHeight() / 2;
	LCUI_BindEvent(LCUI_MOUSEMOVE, OnMouseMoveEvent, NULL, NULL);
	LCUICursor_SetGraph(&pic);
	LCUICursor_Show();
	Graph_Free(&pic);
}
```
I don't know much about linux desktop programming, but in winapi you can change cursor with SetCursor function.

Another one i discovered:
1. Move the cursor inside app area
2. Push left mouse button and drag cursor to the border:
![cursor2](https://user-images.githubusercontent.com/20026104/46599812-f4a1b400-caf0-11e8-907e-2b44b3e4a3be.gif)

Version: 1.0.0 Beta 3 and newer
OS: Win10
Tools: VS 2017 Community

**Comment by lc-soft** [comment]
I found this problem before and made some changes：https://github.com/lc-soft/LCUI/commit/acf9454463ca828c7c245170cf594e08d77d74a1

**Comment by dossalab** [comment]
Thanks for your answer, gonna update to develop I think.
