### ISSUE TITLE
are you ok？

### ISSUE THREAD

**Issue by wellorange** [lc-soft/LCUI#162]
我想重构这个,后端增加vulkan渲染,引擎,ui层用material style的显示层，那样就更完美了，你是否有意向呢？
如果可以可以一块做

**Comment by lc-soft** [comment]
> ui层用material style的显示层

能否详细说明一下？

**Comment by wellorange** [comment]
就是分为三层
1 渲染层用cpu和gpu两种,gpu硬件抛弃opengl 采用vulakn
2 canvas层 实现谷歌的materi design ui
3 然后用于层采用html 或者jsx格式

**Comment by lc-soft** [comment]
这样搞的话，看上改动比较大，可以当成独立的项目重新写了。

**Comment by lc-soft** [comment]
以前有整渲染引擎的想法，但现在已经没这个意向了。

**Comment by wellorange** [comment]
最近整操作系统，搞了好多方案，skia flutter webrender chromuin等各种嵌入式，后来想想，还是自己整一个吧，裁剪Skia for linux ，然后在上层实现material 至于html不要也行，




            
            
                
                    
                            
                                
                            
                            
                                1045923545
                            
                    
                        
                            
                                    邮箱：1045923545@qq.com
                            
                        
                
            
        Signature is customized by Netease Mail Master


On 10/16/2018 21:11, Liu wrote: 以前有整渲染引擎的想法，但现在已经没这个意向了。

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/lc-soft/LCUI","title":"lc-soft/LCUI","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/lc-soft/LCUI"}},"updates":{"snippets":[{"icon":"PERSON","message":"@lc-soft in #162: 以前有整渲染引擎的想法，但现在已经没这个意向了。\r\n"}],"action":{"name":"View Issue","url":"https://github.com/lc-soft/LCUI/issues/162#issuecomment-430231322"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/lc-soft/LCUI/issues/162#issuecomment-430231322",
"url": "https://github.com/lc-soft/LCUI/issues/162#issuecomment-430231322",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [lc-soft/LCUI] are you ok？ (#162)",
"sections": [
{
"text": "",
"activityTitle": "**Liu**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@lc-soft",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"lc-soft/LCUI\",\n\"issueId\": 162,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"lc-soft/LCUI\",\n\"issueId\": 162\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/lc-soft/LCUI/issues/162#issuecomment-430231322"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 393738046\n}"
}
],
"themeColor": "26292E"
}
]
