### ISSUE TITLE
 android/ios support

### ISSUE THREAD

**Issue by patrickkh7788** [lc-soft/LCUI#163]
是否可以添加安卓ios支持呢。。。

**Comment by lc-soft** [comment]
暂不考虑添加。

现在的小 bug 都没怎么花时间去解决呢，你可以等其他对此感兴趣的 android/ios 开发者来贡献代码，但我估计大部分人也不屑于搞这个。

**Comment by patrickkh7788** [comment]
估计很多有兴趣的不是不屑，而是不会。。。。。

**Comment by lc-soft** [comment]
> 估计很多有兴趣的不是不屑，而是不会。。。。。

如果 android/ios 开发者都不知道怎么搞的话，那我这个外行更不知道了。
