### ISSUE TITLE
How to draw bitmap buffer?

### ISSUE THREAD

**Issue by linhuyen** [lc-soft/LCUI#171]
I need to draw **bitmap** from _memory_/_stream_ on **LCUI gui.**
On **Windows**, I can draw it after **LCUI**'s painting via **GDI** _device context_, but I need draw them in order.
- e.g **LCUI gui** -> **my drawing** -> **LCUI popup**/**widget**

```c
LCUI_Widget root, button;

int main()
{
    ...
    LCUI_Init();
    ...
}
             // bitmap format
void onPaint(const void *buffer, int width, int height ...
{
    drawBitmap(buffer, width, height ...
    setOntop(button ...
}
```

<br>

- I found many functions.
- Are they right, how to use them?

https://github.com/lc-soft/LCUI/blob/0ba3e1e70d310672e1ddbff3d45fcf07eb43d19e/include/LCUI/draw/background.h#L42-L44

https://github.com/lc-soft/LCUI/blob/0ba3e1e70d310672e1ddbff3d45fcf07eb43d19e/include/LCUI/painter.h#L33-L37

https://github.com/lc-soft/LCUI/blob/0ba3e1e70d310672e1ddbff3d45fcf07eb43d19e/include/LCUI/surface.h#L79-L88

**Comment by lc-soft** [comment]
You want draw a bitmap on the button widget?

- The Surface_BeginPaint() and Surface_EndPaint() functions are used for framebuffer operations. After an region is rendered, they are called to fill the bitmap into the framebuffer.
- LCUIPainter_Begin() is used to create a region reference in the framebuffer, Let the rendered content only output to this region.

These are the underlying drawing operations, and I think you should draw bitmap in the widget layer.

Maybe you can refer to these code snippets:

- Widget drawing process
    https://github.com/lc-soft/LCUI/blob/develop/src/gui/widget_paint.c#L263-L274
- Custom drawing content of the textview widget
    https://github.com/lc-soft/LCUI/blob/develop/src/gui/widget/textview.c#L425-L450
- Drawing method, support partial region drawing, bitmap data is filled to paint->canvas.bytes
    https://github.com/lc-soft/LCUI/blob/develop/src/draw/background.c#L35-L97
- paint->canvas.bytes can be set to value of HBITMAP object by SetBitmapBits()
    https://github.com/lc-soft/LCUI/blob/develop/src/platform/windows/windows_display.c#L365-L388

**Comment by linhuyen** [comment]
I don't wanna change this source.
Can you give me many **API**s to draw bitmap on the button widget?

**Comment by lc-soft** [comment]
I don't want to take the time to introduce how to use LCUI. If you feel that it is difficult to use, I suggest you use other mature GUI libraries.

**Comment by linhuyen** [comment]
I hope canvas widget will be supported, in next version.
Thank you very much!

**Comment by lc-soft** [comment]
> I hope canvas widget will be supported, in next version.

This is a feature request, you can open a new issue and describe in detail what you need, including the following:

- What do you want to draw?
- What problems did you encounter when drawing these content?
- What API do you want to have? Please give sample code to show how they are used

**Comment by lc-soft** [comment]
The current drawing method is to use a dirty rectangle to mark the redraw region, All component drawing methods need to support partial redrawing, The calculation of the redraw region is troublesome, I will consider adding a flag to turn this feature off for a specific widget.

**Comment by linhuyen** [comment]
@lc-soft 
What is your drawing/rendering technology?

Almost GUIs using real time rendering, e.g **IMGUI**, **NANOGUI** (**OpenGL** based); but **LCUI** has no realtime and no hardware rendering.
I think, **LCUI** using image based (png/jpeg) and widget painter will flush drawing task on it. After image filling done, the surface will render it on window.
