### ISSUE TITLE
Debian package missing .so library file

### ISSUE THREAD

**Issue by lc-soft** [lc-soft/LCUI#177]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%249%20Rewarded-%237E24E3.svg" />](https://issuehunt.io/r/lc-soft/LCUI/issues/177)

**Describe the bug**
Debian package build seems to be incorrect, the package doesn't include .so library file.

**To Reproduce**
1. Run: `sh scripts/make-dist-deb.sh`
2. Go into build/debian directory
3. Open the `lcui_1.3.0-1_amd64.deb` file
4. Check if the .so library file is in the .deb package

**Expected behavior**
the .so library file is in the ,deb package

**Screenshots**

![image](https://user-images.githubusercontent.com/1730073/65369163-9aa3eb00-dc7c-11e9-8788-d931f6c1084d.png)

**Environment (please complete the following information):**
- LCUI version: develop branch
- Build tools: automake
- OS and version: Ubuntu

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $9.00)

- [<img src='https://avatars3.githubusercontent.com/u/1730073?v=4' alt='lc-soft' width=24 height=24> lc-soft](https://issuehunt.io/u/lc-soft) ($9.00)

### Submitted pull Requests
- [#188 build: fix package name in debian control file (#177)](https://issuehunt.io/r/lc-soft/LCUI/pull/188)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/lc-soft/LCUI/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by anshulxyz** [comment]
hi, @lc-soft I'd like to work on this issue
