### ISSUE TITLE
Fontconfig_GetPath() did not get the font file path

### ISSUE THREAD

**Issue by lc-soft** [lc-soft/LCUI#181]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2415%20Rewarded-%237E24E3.svg" />](https://issuehunt.io/r/lc-soft/LCUI/issues/181)

**Describe the bug**

On the Ubuntu system, `Fontconfig_GetPath()` does not correctly get the file location of the default font, the default font actually used is in-core.inconsolata

Console output:
```
...
[font] current font engine is: FreeType
[font] fontconfig enabled
[font] load file: (null)
[font] failed to load file: (null)
[font] load file: (null)
[font] failed to load file: (null)
[font] load file: (null)
[font] failed to load file: (null)
...
```

**To Reproduce**
Run cammnd:

```bash
make
cd test
./helloworld
```

Check console output.

**Expected behavior**
Font file should load correctly.

**Environment (please complete the following information):**
- LCUI version: develop branch
- Build tools: gcc
- OS and version: Ubuntu

**Additional context**

Related code：

https://github.com/lc-soft/LCUI/blob/d52bae5b0368f2d780c980f0e59badcd40c87dfe/src/font/fontlibrary.c#L918-L942

https://github.com/lc-soft/LCUI/blob/d52bae5b0368f2d780c980f0e59badcd40c87dfe/src/font/fontconfig.c#L42-L71

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $15.00)

- [<img src='https://avatars3.githubusercontent.com/u/1730073?v=4' alt='lc-soft' width=24 height=24> lc-soft](https://issuehunt.io/u/lc-soft) ($15.00)

### Submitted pull Requests
- [#187 Fix to get the correct font file path (fix #181)](https://issuehunt.io/r/lc-soft/LCUI/pull/187)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/lc-soft/LCUI/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by d4yvector** [comment]
I would like to try fix it.

**Comment by developerfred** [comment]
hey! I Try solve this.
