### ISSUE TITLE
Broken link in REDME.md

### ISSUE THREAD

**Issue by anshulxyz** [lc-soft/LCUI#184]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%242%20Funded-%2300A156.svg" />](https://issuehunt.io/r/lc-soft/LCUI/issues/184)

**Describe the bug**
The `README.md` mentions a link to the `CONTRIBUTING.md` but that file doesn't exist.
See here: https://github.com/lc-soft/LCUI/blob/develop/README.md#contribution

It sends to this https://github.com/lc-soft/LCUI/blob/develop/CONTRIBUTING.md which is a 404

I would love to contribute to this project but I need instructions to set up the Development Environment.

**Expected behavior**
Sends the developer to documentation for getting started to contribute to your project. Have a look here.

**Screenshots**
![Screenshot from 2019-10-19 14-37-24](https://user-images.githubusercontent.com/6121530/67141115-02e6ec00-f27e-11e9-9359-6c6beda7113e.png)

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $2.00)

- [<img src='https://avatars3.githubusercontent.com/u/1730073?v=4' alt='lc-soft' width=24 height=24> lc-soft](https://issuehunt.io/u/lc-soft) ($2.00)
### Submitted pull Requests
- [#185 docs: update README.md](https://issuehunt.io/r/lc-soft/LCUI/pull/185)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/lc-soft/LCUI/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by lc-soft** [comment]
https://github.com/lc-soft/LCUI/blob/develop/.github/CONTRIBUTING.md
