### ISSUE TITLE
Add FPS meter

### ISSUE THREAD

**Issue by lc-soft** [lc-soft/LCUI#192]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%24185.1%20Funded-%2300A156.svg" />](https://issuehunt.io/r/lc-soft/LCUI/issues/192)

**Is your feature request related to a problem? Please describe.**

We need a graphical user interface to display the current rendering state to debug performance issues.

**Describe the solution you'd like**

Refer the Chrome Browser:

![image](https://user-images.githubusercontent.com/1730073/71359502-92cf4c00-25c7-11ea-9be5-4993acbf4591.png)

This is the list of requirements:

- [ ] Mode
  - [ ] **Normal:** show all content
  - [ ] **Minimized:** only show fps and chart, refer: https://darsa.in/fpsmeter/  
![Peek 2020-07-07 13-27](https://user-images.githubusercontent.com/1730073/86725287-1a5c4400-c05c-11ea-8d80-846fe28a4e55.gif)
  - **Note:** The mode should be switched when clicking it.
- [ ] Charts
  - [ ] **Chart widget:** receive an array of integers and draw them into a bar chart, it should inherit from [canvas](https://github.com/lc-soft/LCUI/blob/develop/src/gui/widget/canvas.c) widget
  - [ ] **FPS chart:** show the number of frames updated every second
  - [ ] **Widget updates chart:** show the number of components updated every second
  - **Note 1:** If nothing is rendered in the current frame then the fps chart should not be updated
  - **Note 2:** All statistics should ignore the effect of the fps meter
- [ ] Labels
  - [ ] Frame Rate
  - [ ] fps: ${fps} fps
  - [ ] fps range: 1-${settings.frame_rate_cap}
  - [ ] Parallel rendering threads: ${used}/${total}
  - [ ] Updates
  - [ ] Updated: ${updatedWidgets}
  - [ ] Total: ${totalWidgets}
  - **Note:** The semantics of these labels may not be clear, you can improve it.
- [ ] APIs
  - [ ] Add APIs to collect the above data
  - [ ] Update the existing APIs to collect the above data
  - **Note:** This work requires many reviews and changes to meet the author's expectations.
- [ ] Use fps meter instead of fps textview in test/test_render.c

**Additional context**

**How to draw a chart?**

You need these:

- i
- x, y
- fps_data
- LCUIWidget_NewPrototype("fps-meter-chart", "canvas")
- Canvas_GetContext()
- `for (x = 0; i < fps_data_length; ++x)`
- CanvasContext_FillRect()

I believe you have guessed the implementation method through these keywords.

**What does it look like?**

I have written css and html code, you can refer to it:

https://codepen.io/lc-soft/pen/NWxYpGv?editors=1100

![2020-07-07 14-02-09 的屏幕截图](https://user-images.githubusercontent.com/1730073/86725134-f993ee80-c05b-11ea-8892-9a537325fe3d.png)

The effect of the bar chart should be the following:

![Peek 2020-07-07 13-27](https://user-images.githubusercontent.com/1730073/86725287-1a5c4400-c05c-11ea-8d80-846fe28a4e55.gif)

https://darsa.in/fpsmeter/

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $185.10)

- [<img src='https://avatars3.githubusercontent.com/u/1730073?v=4' alt='lc-soft' width=24 height=24> lc-soft](https://issuehunt.io/u/lc-soft) ($185.10)

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/lc-soft/LCUI/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by jduo** [comment]
@lc-soft , I can take a look at this. Would it make more sense to have this PR build upon the solution to #191, which I've already made a fair amount of progress on? That work cleans up the profiling code a bit as well as makes the thread count easy to access.

**Comment by lc-soft** [comment]
> @lc-soft , I can take a look at this. Would it make more sense to have this PR build upon the solution to #191, which I've already made a fair amount of progress on? That work cleans up the profiling code a bit as well as makes the thread count easy to access.

Please wait a moment, just now I was thinking about finishing this work when I have time in the future.

**Comment by lc-soft** [comment]
@jduo OK, you can do it.

**Comment by lc-soft** [comment]
@jduo 

The description of this issue needs to be updated. I plan to redesign the requirements of this feature in the future, so please do not consider working on this issue for the time being. Moreover, $100 has exceeded my budget.

![image](https://user-images.githubusercontent.com/1730073/85722956-5cfd5280-b725-11ea-951f-ca151b2d3ec8.png)

**Comment by jduo** [comment]
@lc-soft , this should be re-opened. The settings API commit accidentally referenced this.

**Comment by jduo** [comment]
I'll pick this one up @lc-soft .

**Comment by lc-soft** [comment]
@jduo @jananiram

The description of this issue has been updated, please re-evaluate its workload, and then update the bounty request.

![image](https://user-images.githubusercontent.com/1730073/86726369-14b32e00-c05d-11ea-8b55-332cb07fd1c5.png)

**Comment by lc-soft** [comment]
@jduo 

I think issue #192 is much simpler than issue#210, because the workload of issue #210 is more than 10 times that of issue #192, but from your bounty request, the workload of issue #192 seems to be larger than I expected.

Does this mean Are you planning to make a lot of changes to related code for issue #192? 
Or is issue #210 simpler than I thought?
Please briefly explain your work plan for issue #192。

**Comment by jduo** [comment]
It's mostly the comment "Note: This work requires many reviews and changes to meet the author's expectations." that made me decide to up the bounty on this one from the original $100 I had put up. It was a bit open-ended.

**Comment by lc-soft** [comment]
@jduo I have increased the bonus from $35 to $185.10, and you can start doing it.

**Comment by lc-soft** [comment]
There are three fees in payment, reward and withdrawal: stripe fee (3.74%), service fee (10%), transaction fee (3.6%), I think the fees charged are too much.

**Comment by jduo** [comment]
I've started work on this. A few questions:
1. Should the number of elements in the chart be fixed? Should it be configurable? Should it be dynamic based on the size of the window?
2. Can you point me to an existing widget that inherits from canvas? Do you mean the chart widget should be composed of a canvas widget, such that function calls such as init, onpaint, etc delegate to the canvas widget?
3. Should the chart update every second? The gif updates much more quickly than this. Is every point in the chart a capture of the frame count at a second? I guess the array the chart is built off of needs to be a circular array so that we can add new values without losing previous ones.

**Comment by jduo** [comment]
4. My thinking is that we have a Metrics widget, which holds an FPS meter widget + Widget update stats widget, and the FPS meter widget/widget update stats widget both maintain a chart widget. The application can just construct the Metrics widget. The Metrics widget is responsible for handling changing of the mode between normal/minimized.

**Comment by lc-soft** [comment]
> 1.  Should the number of elements in the chart be fixed? Should it be configurable? Should it be dynamic based on the size of the window?

Do you mean the number of bars in the chart? You can calculate the appropriate number of bars according to the width of the chart, for exmaple:

```c
bars_count = bar_chart.width / bar_width;
```

> 2. Can you point me to an existing widget that inherits from canvas? Do you mean the chart widget should be composed of a canvas widget, such that function calls such as init, onpaint, etc delegate to the canvas widget?

I have written a spinner widget based on canvas widget before, you can refer to it:

https://github.com/lc-ui/lc-design/blob/f824ca5ad6766554312eca44b904ceb5f5cffab7/src/ui/components/spinner.c#L247-L256

![lc-design-spinner](https://user-images.githubusercontent.com/1730073/87143757-34ef2100-c2d9-11ea-8ea2-3f7e92a79629.gif)

The core code is as follows:

- `LCUI_SetInterval(LCUI_MAX_FRAME_MSEC, (TimerCallback)Spinner_OnFrame, w);`
- `static void Spinner_OnFrame(LCUI_Widget w)`
- `static void Spinner_Render(LCUI_Widget w)`
- `LCUI_CanvasContext ctx = Canvas_GetContext(w);`
- `ctx->clearRect(ctx, 0, 0, ctx->width, ctx->height);`
- `FillPixel(&ctx->buffer, xi, yi, &c);`
- `Widget_InvalidateArea(w, NULL, SV_CONTENT_BOX);`
- `ctx->release(ctx);`

> Should the chart update every second? The gif updates much more quickly than this.

Yes, you only need to refer to the color of the bar in the gif, no need to pay attention to the update speed.

> Is every point in the chart a capture of the frame count at a second? 

Yes.

> I guess the array the chart is built off of needs to be a circular array so that we can add new values without losing previous ones.

I suggest using a linked list to save the frame count, the pseudo code is as follows:

```c
LinkedList frameCountList;

// insert new frame count into head
frameCountList.unsift(currentFrameCount);
if (frameCountList.length > maxLen) {
  // delete last frame count
  frameCountList.pop();
}
```

> 4. My thinking is that we have a Metrics widget, ...

I think it's okay, but I want the names of these three components to have the `fps-meter-` prefix.

**Comment by jduo** [comment]
> > 1. Should the number of elements in the chart be fixed? Should it be configurable? Should it be dynamic based on the size of the window?
> 
> Do you mean the number of bars in the chart? I suggest that you calculate the appropriate number of bars based on the width of the chart, for example:
> 
> ```c
> number_of_bars = bar_chart.width / bar_width;
> ```
Would bar_width be fixed then? Or would it scale with the size of the window?
Actually should the chart even be resizable?

**Comment by jduo** [comment]
> > 1. My thinking is that we have a Metrics widget, ...
> 
> I think it's okay, but I want the names of these three widgets to have the `fps-meter-` prefix.
I feel the chart component could potentially be reusable outside of the context of the fps-meter, but I guess we could always rename it.

**Comment by jduo** [comment]
In your example showing CSS/HTML at https://codepen.io/lc-soft/pen/NWxYpGv?editors=1100
Should the CSS you've shown here be passed into LCUI_LoadCSSString()?

**Comment by lc-soft** [comment]
> Should the CSS you've shown here be passed into LCUI_LoadCSSString()?

@jduo Yes, you can use this css code directly and make the widget tree structure the same as the html code.

**Comment by lc-soft** [comment]
> Would bar_width be fixed then? Or would it scale with the size of the window?

it should scale with the size of the window, I think this problem is easy to solve, just recalculate the `bar_width` before each drawing and then draw them with the new `bar_width`.

> Actually should the chart even be resizable?

Yes, this chart widget may be used elsewhere in the future, and you should make it adaptable to any size as much as possible.

**Comment by lc-soft** [comment]
@jduo I thought about it, you can use a fixed width for bar. because there is no need to make the width of the bar scalable, in order to adapt to the large size, we can increase the number of bars instead of increasing the bar width.

**Comment by jduo** [comment]
Hi @lc-soft ,
Was trying to test a build of the widget and noticed the tutorial link was broken here: https://lcui.org/guide/

Quick question, does LCUI create a relationship between CSS properties and struct fields for widgets? Or is that part of the widget implementation?

**Comment by lc-soft** [comment]
@jduo 

There is no English version of this tutorial, and I will replace the tutorial link with https://docs.lcui.lc-soft.io/.

> does LCUI create a relationship between CSS properties and struct fields for widgets?

Check here:

https://github.com/lc-soft/LCUI/blob/6656f40a26d35283b4936203409f3b6119ec4c0b/include/LCUI/gui/widget_base.h#L287-L302

The stylesheet of the widget will be updated here:

https://github.com/lc-soft/LCUI/blob/029984eb173f244803336f94ceb0f194f941c698/src/gui/widget_task.c#L203-L215

CSS properties will be recalculated and saved to `LCUI_Widget::computed_style` when they change.

https://github.com/lc-soft/LCUI/blob/029984eb173f244803336f94ceb0f194f941c698/src/gui/widget_task.c#L175-L196

**Comment by jduo** [comment]
Hi @lc-soft , I got sidetracked for a bit. Plan to come back to this issue next week.

**Comment by lc-soft** [comment]
> Hi @lc-soft , I got sidetracked for a bit. Plan to come back to this issue next week.

OK, If you think this project has some incomprehensible code, please feel free to ask me.

**Comment by Interdice** [comment]
Hi don't know if I can do this, but is this still available?

**Comment by lc-soft** [comment]
> Hi don't know if I can do this, but is this still available?

@Interdice It is temporarily unavailable because the new version under development has many changes, and it needs to wait until the new version is released.
