### ISSUE TITLE
Update test program

### ISSUE THREAD

**Issue by lc-soft** [lc-soft/LCUI#197]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2440%20Funded-%2300A156.svg" />](https://issuehunt.io/r/lc-soft/LCUI/issues/197)

**Is your feature request related to a problem? Please describe.**

The output of the test program should be in the same format.

**Describe the solution you'd like**

Update the following functions in test.c:

https://github.com/lc-soft/LCUI/blob/b87ce34be7a5f4e0cd73da5a2d37d34068bfeb1c/test/test.c#L14-L26

Use the functions in libtest.c instead of `TEST_LOG()`, `CHECK()`, `CHECK_WITH_TEXT()`, just like this:

https://github.com/lc-soft/LCUI/blob/b87ce34be7a5f4e0cd73da5a2d37d34068bfeb1c/test/test_css_parser.c#L114-L145

All output should be formatted like this:

![image](https://user-images.githubusercontent.com/1730073/74605612-a0efa380-5104-11ea-94be-c5d3a5f03570.png)

**Describe alternatives you've considered**
None.

**Additional context**
None.

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $40.00)

- [<img src='https://avatars3.githubusercontent.com/u/1730073?v=4' alt='lc-soft' width=24 height=24> lc-soft](https://issuehunt.io/u/lc-soft) ($40.00)

### Submitted pull Requests
- [#208 test(output): update tests to use libtest.h (fix #197)](https://issuehunt.io/r/lc-soft/LCUI/pull/208)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/lc-soft/LCUI/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by hax0kartik** [comment]
I am willing to do this, however 15$ seems a bit less imho. Could you increase the bounty?

**Comment by hax0kartik** [comment]
I will start working on this, as soon as you increase the bounty

**Comment by lc-soft** [comment]
@hax0kartik Please wait for a few days.

**Comment by lc-soft** [comment]
@hax0kartik What's your expected bounty? I don't want to guess at it.

**Comment by lc-soft** [comment]
@hax0kartik Is there any news on this issue?

**Comment by hax0kartik** [comment]
Hey Liu, I am a bit busy rn, will work on it as soon as i get time.
