### ISSUE TITLE
是否支持arm linux

### ISSUE THREAD

**Issue by hvritual** [lc-soft/LCUI#202]
**Is your feature request related to a problem? Please describe.**
之前用Qt做的，但是qt有很多特性都是不怎么需要的，现在想找一款更加简单、UI开发快速的GUI框架

**Describe the solution you'd like**
能否支持跨平台，如arm-linux(主要是UI用在嵌入式设备上面)，如果是纯C开发应该是可以交叉编译的，但是不支持依赖的底层是否可行

**Describe alternatives you've considered**

**Additional context**

**Comment by lc-soft** [comment]
> 想找一款更加简单、UI开发快速的GUI框架

能否详细说明你的开发需求？方便我确定 LCUI 后续的开发计划

> 能否支持跨平台，如arm-linux(主要是UI用在嵌入式设备上面)，如果是纯C开发应该是可以交叉编译的，但是不支持依赖的底层是否可行

arm-linux 设备上面是什么环境？设备上用的什么 GUI 系统？X11？还是直接靠写帧缓存 (FrameBuffer) 输出图形？

等有空我再给 CI 加上 arm 环境的构建测试，看看支不支持。

**Comment by hvritual** [comment]
感谢回答 arm-linux 目前使用的QT，基于buildroot 编译的，应该是直接靠写帧来输出图形
说开发需求之前，先说一下我的应用痛点：
1、为客户定制嵌入式应用（主要是界面定制，核心业务功能不变）
2、QT商业授权的问题
3、研发成本问题
关于开发需求：
1、首要是支持嵌入式linux
2、能简单支持css动画
3、运行时占用比较小的内存空间
4、跨平台一致性（即多端显示效果一致）

我贴一下硬件环境：imx6ul 256M nand 128M ROM

**Comment by lc-soft** [comment]
> 1、首要是支持嵌入式linux

CI 上 arm64 linux 环境能够构建通过。至于是否能够正常运行，你可以实机测试一下。

![image](https://user-images.githubusercontent.com/1730073/76761959-59276f00-67cb-11ea-9767-011c7f5eb235.png)

> 2、能简单支持css动画

不支持，目前无相关开发计划。

> 3、运行时占用比较小的内存空间

这个得看界面复杂度、加载的字体文件、屏幕大小、CSS 代码量等因素。以下是目前可供测试的程序在 Windows 上的内存占用情况：

- helloworld：7.2MB，最小的应用，可以当成 LCUI 的初始内存占用
- [lcui-router-app](https://github.com/lc-ui/lcui-router-app): 26MB，其中样式表数据占用 17MB，字体数据占用 6.7MB
- [lc-design](https://github.com/lc-ui/lc-design): 29MB，占用情况与上一个大致一样

> 4、跨平台一致性（即多端显示效果一致）

控件都是自绘的，除了字体，效果都是一样的。

**Comment by hvritual** [comment]
ok 我先试一下 感谢作者 问题先关闭了

**Comment by lc-soft** [comment]
@hvritual 上面说到的是开发成本和系统硬件需求，能否再补充说明一下对界面功能的需求？例如：

- 初级：界面内容以按钮、文字和图片为主，用户通过点击按钮实现界面交互
- 高级：需要用到图表、表格向用户展示数据，能够提供多行文本输入框让用户录入数据，用户点击按钮、弹框、切换界面等交互效果需要有过渡动画

**Comment by hvritual** [comment]
不好意思 总算回到嵌入式领域了
界面功能需求，主要是高级
高级：需要用到图表、表格向用户展示数据，能够提供多行文本输入框让用户录入数据，用户点击按钮、弹框、切换界面等交互效果需要有过渡动画
另外还需要能够动态渲染图片数据 如QML
期望系统UI界面有点类似于：https://developer.flythings.cn/zh-hans/docs_brief.html

**Comment by lc-soft** [comment]
> 不好意思 总算回到嵌入式领域了
> 界面功能需求，主要是高级
> 高级：需要用到图表、表格向用户展示数据，能够提供多行文本输入框让用户录入数据，用户点击按钮、弹框、切换界面等交互效果需要有过渡动画
> 另外还需要能够动态渲染图片数据 如QML
> 期望系统UI界面有点类似于：https://developer.flythings.cn/zh-hans/docs_brief.html

对于这个项目而言，以现有的条件，搞 UML 渲染、IDE 和一些高级特性还不太现实，所以用业内成熟的 UI 开发库/框架是最为合适的选择。

**Comment by lc-soft** [comment]
> 不好意思 总算回到嵌入式领域了
> 界面功能需求，主要是高级
> 高级：需要用到图表、表格向用户展示数据，能够提供多行文本输入框让用户录入数据，用户点击按钮、弹框、切换界面等交互效果需要有过渡动画
> 另外还需要能够动态渲染图片数据 如QML
> 期望系统UI界面有点类似于：https://developer.flythings.cn/zh-hans/docs_brief.html

对于这个项目而言，以现有的条件，搞 UML 渲染、IDE 和一些高级特性还不太现实，所以用业内成熟的 UI 开发库/框架是最为合适的选择。

**Comment by lc-soft** [comment]
> 不好意思 总算回到嵌入式领域了
> 界面功能需求，主要是高级
> 高级：需要用到图表、表格向用户展示数据，能够提供多行文本输入框让用户录入数据，用户点击按钮、弹框、切换界面等交互效果需要有过渡动画
> 另外还需要能够动态渲染图片数据 如QML
> 期望系统UI界面有点类似于：https://developer.flythings.cn/zh-hans/docs_brief.html

对于这个项目而言，以现有的条件，搞 UML 渲染、IDE 和一些高级特性还不太现实，所以用业内成熟的 UI 开发库/框架是最为合适的选择。

**Comment by huangelad** [comment]
> > 1、首要是支持嵌入式linux
> 
> CI 上 arm64 linux 环境能够构建通过。至于是否能够正常运行，你可以实机测试一下。
> 
> ![image](https://user-images.githubusercontent.com/1730073/76761959-59276f00-67cb-11ea-9767-011c7f5eb235.png)
> 
> > 2、能简单支持css动画
> 
> 不支持，目前无相关开发计划。
> 
> > 3、运行时占用比较小的内存空间
> 
> 这个得看界面复杂度、加载的字体文件、屏幕大小、CSS 代码量等因素。以下是目前可供测试的程序在 Windows 上的内存占用情况：
> 
> * helloworld：7.2MB，最小的应用，可以当成 LCUI 的初始内存占用
> * [lcui-router-app](https://github.com/lc-ui/lcui-router-app): 26MB，其中样式表数据占用 17MB，字体数据占用 6.7MB
> * [lc-design](https://github.com/lc-ui/lc-design): 29MB，占用情况与上一个大致一样
> 
> > 4、跨平台一致性（即多端显示效果一致）
> 
> 控件都是自绘的，除了字体，效果都是一样的。



> > 1、首要是支持嵌入式linux
> 
> CI 上 arm64 linux 环境能够构建通过。至于是否能够正常运行，你可以实机测试一下。
> 
> ![image](https://user-images.githubusercontent.com/1730073/76761959-59276f00-67cb-11ea-9767-011c7f5eb235.png)
> 
> > 2、能简单支持css动画
> 
> 不支持，目前无相关开发计划。
> 
> > 3、运行时占用比较小的内存空间
> 
> 这个得看界面复杂度、加载的字体文件、屏幕大小、CSS 代码量等因素。以下是目前可供测试的程序在 Windows 上的内存占用情况：
> 
> * helloworld：7.2MB，最小的应用，可以当成 LCUI 的初始内存占用
> * [lcui-router-app](https://github.com/lc-ui/lcui-router-app): 26MB，其中样式表数据占用 17MB，字体数据占用 6.7MB
> * [lc-design](https://github.com/lc-ui/lc-design): 29MB，占用情况与上一个大致一样
> 
> > 4、跨平台一致性（即多端显示效果一致）
> 
> 控件都是自绘的，除了字体，效果都是一样的。

where get the job #1432
