### ISSUE TITLE
DataTable

### ISSUE THREAD

**Issue by bencz** [lc-soft/LCUI#203]
I would like to know about the implementation of DataTable, with filters per column, checkbox column and etc ..., how to get the selected rows on datatable with checkbox.....
From what I looked for, there is still no implementation in the system for that

**Comment by lc-soft** [comment]
**I would like to know about the implementation of DataTable, with filters per column, checkbox column and etc**

Does the DataTable you mean look like this?

![image](https://user-images.githubusercontent.com/1730073/77824256-5b2eed80-713c-11ea-98fc-2f01340102b5.png)

DataTable requires the support of a new layout system to implement it, but  this feature is not included in the development plan of this project, so please check out other similar projects.

**how to get the selected rows on datatable with checkbox**

As far as I know, there are two solutions:

1. Add an event binding for each checkbox in the DataTable, and when the checked event is triggered,, mark the bound data row as checked.The pseudo code is as follows:
1. When you need to submit data, iterate through each row in the DataTable. If the checkbox of the row is checked, the data of the row is recorded. The pseudo code is as follows:
    ```cpp
    DataTable table;
    Arary yourData;
    Array selectedRows = [];

    table.children.forEach((row, index)=> {
        if (row.querySelector('checkbox').checked) {
            selectedRows.push(yourData[index]);
        }
    })
    ```

**Comment by bencz** [comment]
Good morning, from Brazil!
Thanks for your response.
Yes, when I asked about the datatable, it was just that type
Well, no problem .... I saw that you also do sponsored development, how much would it be necessary for you to develop data-table support?

When I asked about getting data from the data-table, it would be using your lib!

**Comment by lc-soft** [comment]
**I saw that you also do sponsored development, how much would it be necessary for you to develop data-table support?**

I do n’t have time to develop complex new features now and in the next few months. Sponsored development will make me feel pressured. I just want to make my life easier, so please let me reject your request.

**Comment by bencz** [comment]
Oh, ok!!
No problem, you are right! :)
Thank you!!
