### ISSUE TITLE
Add clipboard support

### ISSUE THREAD

**Issue by lc-soft** [lc-soft/LCUI#216]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%242%20Rewarded-%237E24E3.svg" />](https://issuehunt.io/r/lc-soft/LCUI/issues/216)

**Is your feature request related to a problem? Please describe.**

Sometimes we need to paste some content into the input box, but LCUI does not support it.

**Describe the solution you'd like**

Add clipboard support to meet the following requirements:

- [ ] **textedit:** CTRL+V should be able to insert the content of the clipboard to the caret position.
- [ ] Should work on Linux.
- [ ] Should work on Windows.

**Describe alternatives you've considered**

None.

**Additional context**

You can refer to the source code of SDL:

- https://github.com/SDL-mirror/SDL/blob/master/src/video/SDL_clipboard.c
- https://github.com/SDL-mirror/SDL/blob/master/src/video/windows/SDL_windowsclipboard.c
- https://github.com/SDL-mirror/SDL/blob/master/src/video/x11/SDL_x11clipboard.c

**Note:**  If you think you can do it, please request a bounty on [issuehunt.io](https://issuehunt.io/r/lc-soft/LCUI/issues/216) to tell everyone how much bounty you need. If you think this feature is necessary, you can also fund this issue on  [issuehunt.io](https://issuehunt.io/r/lc-soft/LCUI/issues/216).

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $2.00)

- [<img src='https://avatars.githubusercontent.com/u/1730073?v=4' alt='lc-soft' width=24 height=24> lc-soft](https://issuehunt.io/u/lc-soft) ($2.00)

### Submitted pull Requests
- [#271 feat(platform): add clipboard support](https://issuehunt.io/r/lc-soft/LCUI/pull/271)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/lc-soft/LCUI/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by tangxg** [comment]
@lc-soft   win上  一些组合键输入乱码  例如：ctrl+v  ctrl+n  等。
顺便附上 ctrl+v  win32实现
```c
static void OnKeyup(LCUI_Widget w, LCUI_WidgetEvent e, void *arg)
{
	if (e->key.code == 229 || e->key.code == 86)
	{
		if (LCUIKeyboard_IsHit(17))
		{
			OpenClipboard(NULL);
			HGLOBAL hGlobal = NULL;
			hGlobal = GetClipboardData(CF_UNICODETEXT);
			wchar_t *pGlobal = (wchar_t *)GlobalLock(hGlobal);
			CloseClipboard();
			TextEdit_InsertTextW(w, pGlobal);
		}
	}
}
```

**Comment by lc-soft** [comment]
@tangxg 这方式获取到的是纯文本吗？如果剪切板里有图片或富文本内容，那获取到的是什么内容？

**Comment by tangxg** [comment]
@lc-soft  目前只是在win10上测试过  获取（word,网页，VS编辑器，富文本编辑器等等）是纯文本，其他未测试过。
我看了下WIN32API  复制文件时应该可以取到 路径 测试发现内存地址都没得 是个NULL。

**Comment by WhoAteDaCake** [comment]
@lc-soft  How would you expect the feature to be implemented? I assume the approach would be adding clipboard.c to platform (and equivalent linux_x11clipboard.c)

But then, how would the copy event be handled, It doesn't seem synchronous. The linked SDL approach seems to have a blocking while loop, however, I've seen another implementation, which can be found [here](https://github.com/exebook/x11clipboard/blob/master/x11paste.c). The explanation I've found was

> As you ask another application to prepare the buffer, and that may take some time, the request is asynchronous: the owner prepares the buffer, saves it in a specified location (window property is used as a temporary storage) and notifies you with SelectionNotify event when it's done.

So I'm not certain you can just request `XNextEvent` and guarantee that next event will be `SelectionNotify`.

**Comment by lc-soft** [comment]
@WhoAteDaCake

Sorry, there are some problems with my comments above, the idea described in my comment is only suitable for read clipboard content when CTRL+V is pressed, not for read clipboard content at any time.

I redesigned the usage of the Clipboard API. The example pseudo code is as follows:

```c
typedef struct LCUI_TextEditRec_ {
	// ...

	LCUI_Clipboard clipboard;
};

void TextEdit_OnInit(LCUI_Widget w)
{
	// ...

	// Create a clipboard object for storing clipboard data
	textedit->clipboard = LCUI_CreateClipboard();

	// ...
}

void TextEdit_OnDestroy(LCUI_Widget w)
{
	// ...

	LCUI_DestroyClipboard(textedit->clipboard);
	textedit->clipboard = NULL;

	// ...
}

void TextEdit_OnPaste(LCUI_Widget w, LCUI_WidgetEvent e, void *arg)
{
	const char *text;
	const wchar_t *wtext;
	LCUI_Clipboard cb = arg;

	if (Clipboard_HasText(cb)) {
		text = Clipboard_GetText(cb);

		// Convert to unicode string
		// ...

		TextEdit_InsertTextW(w, wtext);
	}
}


// In Linux x11, this function will be called when SelectionNotify event is received
void TextEdit_OnClipboardReady(LCUI_Clipboard clipboard, void *arg)
{
	LCUI_Widget w = arg;
	LCUI_WidgetEventRec e = { 0 };

	LCUI_InitWidgetEvent(&e, "paste");
	Widget_TriggerEvent(w, &e, clipboard);
}

void TextEdit_OnKeyDown(LCUI_Widget w, LCUI_WidgetEvent e, void *arg)
{
	LCUI_Clipboard clipboard;
	LCUI_TextEdit textedit;

	// ...

	if (is pressed Ctrl+V) {
		// Asynchronously preparing clipboard data
		// In linux x11, it will call XConvertSelection()
		LCUI_UseClipboard(textedit->clipboard, TextEdit_OnClipboardReady, w);
	}
}
```

**Note:**

- No `LCUI_PASTE` and `LCUI_PASTE_READY` events
- The clipboard does not need to care about keyboard events

**Comment by WhoAteDaCake** [comment]
@lc-soft 

Wouldn't storing clipboard at widget, rather than system level cause problems? If we wan't to support CTRL+C feature, we'd need to support `SelectionRequest` event (It would come if some other window asks for the the text we copied), meaning we need access to clipboard selected text from within `linux_x11clipboard.c`.

I'd propose, we keep the `clipboard` data as part of each system file `linux_x11clipboard.c`, `windows_clipboard.c` etc.

**Comment by lc-soft** [comment]
@WhoAteDaCake

Well, storing the clipboard in widgets would increase the cost and implementation complexity of the clipboard API, so I think we can choose to store the clipboard at the system level.
