### ISSUE TITLE
Abnormal rendering of Chinese characters.

### ISSUE THREAD

**Issue by tangxg** [lc-soft/LCUI#221]
以解决字体库名字 不统一引起

补充说明： 后续测试发现 WIN7渲染正常 win10才会出现异常。其他环境未测试过。

Problem description:
1. Project depends on LCDesign LCUI
2. Resource reference LC-design.css Custom CSS
3. Normal Rendering in English is abnormal when Chinese characters appear. For example: in four cases, either the first two words are small, or the second two words are small.

For example, the "直接打印" strokes in "直" are rendered incorrectly.
Code examples:
`<?xml version="1.0" encoding="UTF-8" ?>
<lcui-app>
  <resource type="text/css" src="assets/stylesheets/SharedPrinting.css"/>
  <resource type="text/css" src="assets/stylesheets/lc-design.css"/>
  <ui>
    <home>
      <w class="title">
        <p>直接打印</p>
      </w>
    </home>
  </ui>
</lcui-app>
`

问题描述：
   1.项目依赖  LCDesign LCUI
   2.资源引用  lc-design.css 自定义CSS
   3. 英文渲染正常当出现汉字时异常。例如：四个情况下，不是前面两个字小点就是后面2个字小点。
例如”直接打印“ 当中的”直“ 笔画都渲染错了。
代码示例：
`<?xml version="1.0" encoding="UTF-8" ?>
<lcui-app>
  <resource type="text/css" src="assets/stylesheets/SharedPrinting.css"/>
  <resource type="text/css" src="assets/stylesheets/lc-design.css"/>
  <ui>
    <home>
      <w class="title">
        <p>直接打印</p>
      </w>
    </home>
  </ui>
</lcui-app>
`

**Comment by lc-soft** [comment]
直接用中文就可以了。

**Comment by tangxg** [comment]
> 问题描述可以用中文，建议附上截图。

官方旗舰引用 LC-Finder 在WIN10 也会出现我说那个问题  刚刚继续测试 发现部分控件无法 修改字体  text  button
由此引发在lc-design.css 定义的默认样式不生效。

**Comment by lc-soft** [comment]
@tangxg 字体是每个控件都得单独设置，因为目前 css 没有继承功能，不能从父级继承字体样式。
