### ISSUE TITLE
Link error in msvc v142

### ISSUE THREAD

**Issue by HydrogenC** [lc-soft/LCUI#222]
**Describe the bug**

**To Reproduce**
1. Compile and link the LCUI example program with MSVC v142

**Expected behavior**
Runs normally. 

**Screenshots**
```
错误	C1047	对象或库文件“C:\Users\LZMPDev\Downloads\LCUI-2.1.0_x64-windows.lcpkg\lib\LCUIMain.lib”是使用比创建其他对象所用编译器旧的编译器创建的；请重新生成旧的对象和库
C:\Users\LZMPDev\Source\Repos\LCTest\LCTest\LINK	1	
```

**Environment (please complete the following information):**
- LCUI version: 2.1.0
- Build tools: VS2019
- OS and version: Win10

**Additional context**

**Comment by lc-soft** [comment]
试试安装 v141_xp 工具集，然后修改项目配置，使用此工具集编译项目。

https://github.com/MicrosoftDocs/cpp-docs/issues/1810

**Comment by HydrogenC** [comment]
请问LCUI是因为要兼容WinXP而默认使用v141的吗

**Comment by lc-soft** [comment]
> 请问LCUI是因为要兼容WinXP而默认使用v141的吗

因为 Windows 的适配代码是基于 WinXP 的 API 实现的。

**Comment by HydrogenC** [comment]
好的，谢谢

**Comment by HydrogenC** [comment]
@lc-soft 鉴于v141已经不受支持，能否在今后的发行版中加入v142的二进制文件，谢谢？

**Comment by HydrogenC** [comment]
禁用全程序优化可以解决此问题。
