### ISSUE TITLE
Cant build project ft2build.h: No such file or directory

### ISSUE THREAD

**Issue by FightForDobro** [lc-soft/LCUI#223]
when building I am get error

freetype.c:40:10: fatal error: ft2build.h: No such file or directory
   40 | #include <ft2build.h>
      |          ^~~~~~~~~~~~
compilation terminated.

**Comment by lc-soft** [comment]
How did you build it? Please check whether the command you run and its output are the same as GitHub Actions: https://github.com/lc-soft/LCUI/runs/1056914187

**Comment by FightForDobro** [comment]
When I run ./configure, I have a difference in this line
GitHub Actions:
Build with fontconfig support ...... : yes
My result:
Build with fontconfig support ...... : no

Full result:
Build with lcui-builder support .... : yes
Build with libpng support .......... : yes
Build with libjpeg support ......... : yes
Build with font-engine support ..... : freetype2
Build with fontconfig support ...... : no
Build with thread support .......... : pthread
Build with OpenMP support .......... : yes
Build with video support ........... : x11

**Comment by lc-soft** [comment]
@FightForDobro please upload config.log file
