### ISSUE TITLE
Unable to execute `lcui create myapp`

### ISSUE THREAD

**Issue by ZhUyU1997** [lc-soft/LCUI#225]
**Describe the bug**
After installing @lcui /cli by cnpm, unable to execute `lcui create myapp`

**To Reproduce**
1. sudo cnpm install -g @lcui/cli
2. lcui create myapp
After my check, I modify the "/usr/local/bin/lcui" attribute from CRLF to LF, then work fine. I think this is the key.

**Screenshots**
![image](https://user-images.githubusercontent.com/18410894/94683414-125d2900-0359-11eb-8d8d-0b4db767fe9b.png)

**Environment (please complete the following information):**
- OS and version: Ubuntu 20.04

**Comment by lc-soft** [comment]
这个命令暂时只适用于 Windows 系统。

**Comment by d1y** [comment]
> **Describe the bug**
> After installing @lcui /cli by cnpm, unable to execute `lcui create myapp`
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
>     1. sudo cnpm install -g @lcui/cli
> 
>     2. lcui create myapp
>        After my check, I modify the "/usr/local/bin/lcui" attribute from CRLF to LF, then work fine. I think this is the key.
> 
> 
> **Screenshots**
> ![image](https://user-images.githubusercontent.com/18410894/94683414-125d2900-0359-11eb-8d8d-0b4db767fe9b.png)
> 
> **Environment (please complete the following information):**
> 
>     * OS and version: Ubuntu 20.04

用 `npm -g` 就可以
