### ISSUE TITLE
 lcpkg run start 就missing script: [object Object]

### ISSUE THREAD

**Issue by zhangjianhong111** [lc-soft/LCUI#231]
**Describe the bug**

**To Reproduce**
1. [First Step]
2. [Second Step]
3. [Other Steps...]

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
- LCUI version: [Enter LCUI version here]
- Build tools: [Enter build tools name and version here, E.g: gcc/clang/VisualStudio 201X]
- OS and version: [Enter OS name and version here, E.g: WinXP/Win7/Win10/Ubuntu/Mac OS]

**Additional context**

**Comment by lc-soft** [comment]
详见 lc-ui/lcui-router-app#2 的评论。
