### ISSUE TITLE
Add WebView

### ISSUE THREAD

**Issue by niutech** [lc-soft/LCUI#232]
Please add a lightweight WebView widget to embed an arbitrary web page in a sandbox, possibly using a native browser engine with [webview](https://github.com/webview/webview), [Ultralight](https://github.com/ultralight-ux/Ultralight) or [Servo](https://github.com/servo/servo). Thanks!

**Comment by lc-soft** [comment]
Before adding WebView widget, we need to solve the following problems:

1.  **How to compile browser engine easily and quickly?**
    The browser engine may have many dependent libraries, and the compilation methods of these libraries are various. 
We should provide a few simple command lines to make it easier for users to compile it.
1. **How to adapt browser engine?**
    We need to transfer UI events to WebView and present the rendering results of WebView output to the screen. Does WebView provide relevant API support?

If you have used these browser engines, studied its source code, and can provide solutions to these problems, it will be very helpful for the development of WebView widget.

**Comment by niutech** [comment]
I have used Ultralight (free for non-commercial and companies with <$100k revenue) and it's very simple to integrate, have a look at the [quick start tutorial](https://docs.ultralig.ht/docs/writing-your-first-app).

Another option is to use the native platform web engine, see the [webview sample](https://github.com/webview/webview#webview-for-cc-developers) - you just have to `#include "webview.h"` and provide the native window handle in `webview_create(int debug, void *window)`.

**Comment by niutech** [comment]
@lc-soft What does it mean that it's resolved as completed?

**Comment by lc-soft** [comment]
> @lc-soft What does it mean that it's resolved as completed?

It means rejected.
Because I have no plans to add webview support.
