### ISSUE TITLE
Producing binaries

### ISSUE THREAD

**Issue by WhoAteDaCake** [lc-soft/LCUI#235]
**Is your feature request related to a problem? Please describe.**
It's more of a question. I've noticed that the last release was in 5 Jul 2020 even though there has been way more recent commits. Is it possible that you do have to do it manually ? If so I could try and help setting up github actions to automate this.

**Describe the solution you'd like**
I could try and implement it via github actions.

**Comment by lc-soft** [comment]
> Is it possible that you do have to do it manually ? 

Yes it is. I will manually download binary files from AppVeyor CI and GitHub Actions every time I create a release and upload them as release assets. 

> If so I could try and help setting up github actions to automate this.

Does this mean you are interested in updating the configuration file of GitHub actions so that it can build binary packages for Linux and Windows?

**Comment by WhoAteDaCake** [comment]
Yes, i'll give it a shot later today and possibly tomorrow, se where I get to

**Comment by WhoAteDaCake** [comment]
So I've been taking a look at it, but it keeps hitting the issue of :
> error MSB8020: The build tools for Visual Studio 2017 (Platform Toolset = 'v141') cannot be found.

I have been trying to fix it with multiple approaches, but it's taking it's time. I feel like if I keep using Visual studio I'll keep hitting these issues
Is there a way of building this on windows without a visual studio?

**Comment by lc-soft** [comment]
> error MSB8020: The build tools for Visual Studio 2017 (Platform Toolset = 'v141') cannot be found.

What is your build environment? This error message seems to be because you are using another version of Visual Studio to build. 

> Is there a way of building this on windows without a visual studio?

I don't think Visual Studio is necessary. If you can pass the correct parameters to the compiler and linker like Visual Studio, then you can successfully build LCUI.

But adding other build methods will increase maintenance costs, so I suggest you use Visual Studio to build.

**Comment by WhoAteDaCake** [comment]
Fair point, it would be more costly.
I was using windows-2019 build environment
> https://github.com/WhoAteDaCake/LCUI/runs/2645699958?check_suite_focus=true

After switching to windows-2016, I encountered another issue
> https://github.com/WhoAteDaCake/LCUI/runs/2645744382?check_suite_focus=true

I'll investigate further later

**Comment by WhoAteDaCake** [comment]
I think I've managed to build, will finish it off and try sharing with you. Unfortunately I do not have windows laptop, so I can't test.

On another note, what's the prefered way of sharing release notes ? I've seen other people create docs/release-notes/$VERSION.md. This way github actions can release that content together fill official release

**Comment by lc-soft** [comment]
> I was using windows-2019 build environment

Maybe you can use the `devenv LCUI.sln /upgrade` command to upgrade the platform toolset of the solution file from 2017 to 2019.

https://docs.microsoft.com/en-us/visualstudio/ide/reference/upgrade-devenv-exe?view=vs-2019

> Unfortunately I do not have windows laptop, so I can't test.

You can add a job to GitHub Actions, let it build build\windows\LCUI-Demo.sln, and then run LCUITest.exe to test whether LCUI is working properly. 

The path of the LCUITest.exe file is: `bin\x64-windows\Debug\LCUITest.exe`, Its working directory should be set to: `test\`.

> On another note, what's the preferred way of sharing release notes?

Run `npm run update-changelog` command to generate a change log. It collects the commits from the previous version to the current version, and then generates a change log and outputs it to the CHANGELOG.md file. 

> I've managed to get a build on windows, is there a way for you to verify it works ? 

![image](https://user-images.githubusercontent.com/1730073/119250387-5ba50600-bbd2-11eb-8565-192ccbc8b6ea.png)

This file is too big, we should upload each file as shown below instead of packaging them into one file. 

![image](https://user-images.githubusercontent.com/1730073/119250533-42e92000-bbd3-11eb-99ef-7bf1690aee5b.png)

**Comment by WhoAteDaCake** [comment]
Thanks, I'll try to test that. I'll take a look at update-changelog to see if I can pull the changeling notes to push with the release.

> This file is too big, we should upload each file as shown below instead of packaging them into one file.

Yes the files will be added as separate entries, this is just a build artifact, to be downloaded and extracted before release

**Comment by WhoAteDaCake** [comment]
I've ran the test, but it seems to be failing, could you let me know what i did wrong? 
https://github.com/WhoAteDaCake/LCUI/runs/2668570266?check_suite_focus=true#step:13:469

**Comment by lc-soft** [comment]
> I've ran the test, but it seems to be failing, could you let me know what i did wrong?

I will fix the test failure. You can let GitHub actions ignore the error of this step and continue with the next step.

> on ubuntu, would you want me to build using lcpkg or make and what command did you use to package ubuntu dependencies ?

Using make.

The existing Ubuntu build script works well, and I think it can continue to be used.

https://github.com/lc-soft/LCUI/blob/38d44608ba0cca660a2f928420df09af57fe7836/.github/workflows/ccpp.yml#L5-L31

**Comment by lc-soft** [comment]
I found that the `√` is displayed as `?`. Is this problem easy to fix?

![image](https://user-images.githubusercontent.com/1730073/119598970-9d25f300-be16-11eb-825c-6924d70d4a40.png)

![image](https://user-images.githubusercontent.com/1730073/119598971-9d25f300-be16-11eb-9913-925b48cf6e52.png)

**Comment by WhoAteDaCake** [comment]
I tried replacing it with other characters, but it seems that github actions terminal dislikes ut8 characters

**Comment by WhoAteDaCake** [comment]
One more question, in regards of versioning, do you want the versioning to be more automated?
At the moment, they are all hardcoded in config files, we could use an environment variable, to make that configurable.

If it's not too important right now, I can get the build working first and change it once it's merged

**Comment by lc-soft** [comment]
> One more question, in regards of versioning, do you want the versioning to be more automated?

Yes, I want, I often forget to change the version in some files when I release a new version,, so I want to have the script automatically update the version.

But it's not too important right now, You can get the build working first and change it once it's merged.

> Side note: I can't build debian distribution because tests keep failing ?

![image](https://user-images.githubusercontent.com/1730073/119919216-89a49480-bf9c-11eb-8bd0-9166e5b94a43.png)

This problem has been solved recently. You can pull the latest code from the develop branch.

**Comment by WhoAteDaCake** [comment]
Finally got a release working https://github.com/WhoAteDaCake/LCUI/releases
Does that look ok ?

**Comment by WhoAteDaCake** [comment]
If that's fine, I'll branch from develop, to clean up the comits and create a pull request

**Comment by lc-soft** [comment]
Nice.

**Comment by WhoAteDaCake** [comment]
Open in https://github.com/lc-soft/LCUI/pull/237
