### ISSUE TITLE
Modal Window Still Clickable

### ISSUE THREAD

**Issue by TheSystemIsCorrupt** [lc-soft/LCUI#261]
**Describe the bug**
If we make a window modal while using lcui window will be still clickable and it just stop update rendering.

**To Reproduce**
1. Create your application
2. Create a button
3. Execute a message box on button click
4. Click on the button again without closing message box

**Expected behavior**
Inputs must be blocked when a window is in modal mode.

**Environment (please complete the following information):**
- LCUI version: 2.2
- Build tools: VS 2022

**Comment by lc-soft** [comment]
Message box ? Did you create it by calling the [`MessageBox()`](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-messagebox) function of Win32 API?

**Comment by TheSystemIsCorrupt** [comment]
Yes

**Comment by lc-soft** [comment]
You can try to disable the button before calling `MessageBox()`:

```c
Widget_SetDisabled(your_button, TRUE);
```

Or block event handling:

```c
Widget_BlockEvent(LCUIWidget_GetRoot(), TRUE);
```
