### ISSUE TITLE
默认的例子最大化后再最小化，控件都没了。

### ISSUE THREAD

**Issue by Killea** [lc-soft/LCUI#282]
**Describe the bug**
![image](https://user-images.githubusercontent.com/5551824/154851536-75dea6f4-6a65-47da-81a5-50346b569448.png)
我想知道这是类库的bug还是例子程序的bug。屏幕是4K屏幕不知道是否有关。

**To Reproduce**
1. [First Step]
2. [Second Step]
3. [Other Steps...]

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
- LCUI version: [Enter LCUI version here]
- Build tools: [Enter build tools name and version here, E.g: gcc/clang/VisualStudio 201X]
- OS and version: [Enter OS name and version here, E.g: WinXP/Win7/Win10/Ubuntu/Mac OS]

**Additional context**

**Comment by lc-soft** [comment]
库的 bug。

**Comment by lc-soft** [comment]
建议提供录屏。

**Comment by lc-soft** [comment]
建议录屏发上来。
