### ISSUE TITLE
C++ 相关问题

### ISSUE THREAD

**Issue by 204065248** [lc-soft/LCUI#289]
刚刚我问了支不支持C++，我已经看到demo了，但是还有几个疑问。
1. C++有创建项目的工具吗，还是说自己组装项目目录。
2. 编译仍然用文档中的方式吗
3. 可否将布局资源和图片资源加载制作成压缩包嵌入到资源中呢

**Comment by lc-soft** [comment]
1. 没有。你需要自己组装项目目录。
2. 是的。这个项目只提供了 VisualStuido 的工程文件，编译前需要先用 lcpkg 安装第三方库，或者你也可以用 vcpkg 安装，然后手动复制它们的头文件和库文件 (.dll .lib) 到特定目录中。
3. 可以。但本项目不提供此功能，你需要借助第三方库/工具来做，或者你也可以自己设计一种文件格式来容纳各种资源文件，只需要制定文件内容格式，然后编写代码实现文件读写操作。

**Comment by 204065248** [comment]
> 1. 没有。你需要自己组装项目目录。
> 2. 是的。这个项目只提供了 VisualStuido 的工程文件，编译前需要先用 lcpkg 安装第三方库，或者你也可以用 vcpkg 安装，然后手动复制它们的头文件和库文件 (.dll .lib) 到特定目录中。
> 3. 可以。但本项目不提供此功能，你需要借助第三方库/工具来做，或者你也可以自己设计一种文件格式来容纳各种资源文件，只需要制定文件内容格式，然后编写代码实现文件读写操作。

谢谢解答
