### ISSUE TITLE
textedit相关问题

### ISSUE THREAD

**Issue by 204065248** [lc-soft/LCUI#291]
1. textedit无法Ctrl + A全选吗，按了后出现下图情况
![image](https://user-images.githubusercontent.com/17307843/187886193-7e5e67cb-4540-4854-8e14-c3d6a9e93709.png)
2. 无法选中文本
3. 双击无法全选

另外我想问问，2.2版本如何实现多窗效果。如果不行的话3.0版本什么时候发布呢

**Comment by 204065248** [comment]
哦，还有如何设置全局样式，比如说设置全局的字体。

**Comment by lc-soft** [comment]
textedit 没做文本选中功能，不支持 Ctrl+A 快捷键全选
