### ISSUE TITLE
希望可以添加对android的支持

### ISSUE THREAD

**Issue by woodzn** [lc-soft/LCUI#301]
我找过很多C语言或C++的图形库，很少有对android提供支持的。
少部分支持android的图形库，界面UI不够美观
希望作者能搞添加对android的支持，弥补这块空缺

**Comment by lc-soft** [comment]
已有相同的问题：#210，没人愿意做。之前我去外包平台发项目也没人接，主要原因是钱给少了，但给多了还不如我自己搞。

目前并没有 Android 的适配计划，毕竟 Android 开发者已经有不少成熟的 UI 开发技术可以选择，要是跟这些技术相比没有什么优势的话，还不如不搞。

如果你感兴趣，可以提供一些功能设计方面的建议，以及一些参考资料。

另外，界面 UI 是否美观取决于开发者的设计水平，与 UI 库没多大关系。
