### ISSUE TITLE
请问哪里能下载比v0.12.4更早版本的源代码？

### ISSUE THREAD

**Issue by guoshimin57** [lc-soft/LCUI#307]
如题。在这里问这个问题可能不太合适，但我不知道在哪里问更合适。我想找更早的版本，代码量少一些，容易领悟整个项目的架构。

**Comment by lc-soft** [comment]
没有更早版本的代码了。

你可以参考现有两个版本的文档来了解这个项目的部分设计。

- v3.x 版本：https://lcui-dev.github.io/docs/next/rfcs/lcui/architecture
- v2.x 版本：https://docs.lcui.lc-soft.io/

如果你觉得有些地方不容易理解的话，可以列个问题清单。
