### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [lc-soft/LCUI#31]
I would like to point out that an identifier like "[`__LCUI_WIDGET_EVENT_H__`](https://github.com/lc-soft/LCUI/blob/502b23c40504072ae6f957e3bdf67f9b55316c51/include/LCUI/gui/widget_event.h#L40)" [does not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by lc-soft** [comment]
ok, I know, you are already said it again.

**Comment by lc-soft** [comment]
the C language standard also has such this identifier naming rule ?

**Comment by elfring** [comment]
Yes. - [It is similar](https://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier#answer-228797 "What are the rules about using an underscore in a C++ identifier?").

Thanks for [your improvements of affected include guards](https://github.com/lc-soft/LCUI/commit/72d2636fc54105348ae6287fb24eb6f462c7373d "Deletion of some underscores").

**Comment by elfring** [comment]
Thanks for [further source code improvements](https://github.com/lc-soft/LCUI/commit/de711ef7ec8237c4cdbedbd07625365863ca6499#diff-8d22817da02151edd2c38c5e6c5c6673L37 "Renaming of include guards").

**Comment by lc-soft** [comment]
If there are no other problems, you should choose to close this issue.
