### ISSUE TITLE
#define ⇒ enum?

### ISSUE THREAD

**Issue by elfring** [lc-soft/LCUI#32]
Would you like to replace more defines for constant values by [enumerations](https://en.wikipedia.org/wiki/Enumerated_type#C_and_syntactically_similar_languages) to stress their relationships?
* [FILE_ERROR_…](https://github.com/lc-soft/LCUI/blob/34391f87400e8458e05f067002d95f722e487675/include/LCUI/draw.h#L47)
* [MAX_…](https://github.com/lc-soft/LCUI/blob/47adab494d276b3c976c9117d029444b0a489e7b/src/gui/widget_style.c#L47)

**Comment by lc-soft** [comment]
There is no relationship between `MAX_... `, so they are not suitable for use the  enumerations。

As for `FILE_ERROR_...`, I plan to cancel them.
