### ISSUE TITLE
Complete build options for Pthread API

### ISSUE THREAD

**Issue by elfring** [lc-soft/LCUI#33]
Would you like to add the configuration script "[AX_PTHREAD](https://www.gnu.org/software/autoconf-archive/ax_pthread.html "How to build C programs using POSIX threads?")" to [your build specification](https://github.com/lc-soft/LCUI/blob/57567f945da2f65eaf741222ee738e2b3f6cbaec/configure.ac#L63 "Configuration checks")?

**Comment by lc-soft** [comment]
check [here](https://github.com/lc-soft/LCUI/commit/838752650a05d19144594c807f1a95c12e7b37a3#diff-67e997bcfdac55191033d57a16d1408aL68).

**Comment by elfring** [comment]
Is there any [more fine-tuning needed for the affected configuration script](https://github.com/lc-soft/LCUI/commit/838752650a05d19144594c807f1a95c12e7b37a3#diff-67e997bcfdac55191033d57a16d1408aR65 "Update candidate")?

**Comment by lc-soft** [comment]
check [here](https://github.com/lc-soft/LCUI/commit/5697ab5cea12edcb0ec8885206ab5397a0dd4093#diff-67e997bcfdac55191033d57a16d1408aR63).
