### ISSUE TITLE
Protect against spurious wakeups

### ISSUE THREAD

**Issue by elfring** [lc-soft/LCUI#34]
I have seen that [no loop is used around a call](https://github.com/lc-soft/LCUI/blob/57567f945da2f65eaf741222ee738e2b3f6cbaec/src/util/framectrl.c#L105 "Check FrameControl_Remain()") of the function "[LCUICond_Wait](https://github.com/lc-soft/LCUI/blob/6d210d988958131e2949fcdfa8ffcf7291c217e0/src/thread/pthread/cond.c#L60 "Wait on a condition")".
Would you like to reuse anything from my message on the topic "[spurious wakeup](http://groups.google.de/group/comp.programming.threads/msg/bb8299804652fdd7 "Discussion about handling of spurious wakeups")"?

**Comment by lc-soft** [comment]
I think `spurious wakeups` will not cause a very serious problem in [this function](https://github.com/lc-soft/LCUI/blob/develop/src/display.c#L377) , just not very often.

**Comment by elfring** [comment]
I suggest to reconsider the consequences of "notifications" that can be spurious.
How do you think about to fix the checking of predicates around condition variable usage in your software?

**Comment by lc-soft** [comment]
When spurious wakeups or timeout, after pthread_cond_timedwait () exit, the mutex lock will be locked ?
``` c
...
pthread_mutex_lock( &mutex );
if( pthread_cond_timedwait( &cond, &mutex, &ts ) != 0 ) {
        /* mutex is locked ? */
}
pthread_mutex_unlock( &mutex );
...
```

**Comment by elfring** [comment]
I suggest to take another look at [condition variable usage](http://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_cond_signal.html#tag_16_418_08 "Signal a condition").
Is [the implementation of the function "FrameControl_Remain"](https://github.com/lc-soft/LCUI/blob/72d2636fc54105348ae6287fb24eb6f462c7373d/src/util/framectrl.c#L105 "Update candidate") the only place where a checking of the corresponding predicate was missed in your software?

**Comment by lc-soft** [comment]
like this ?
![29ae51095503c6c902b4eadce3f1db8e_r](https://cloud.githubusercontent.com/assets/1730073/15665865/391e1db4-2740-11e6-843f-0ca703c0ccdc.jpg)

**Comment by lc-soft** [comment]
Not only `FrameControl_Remain()`, [`LCUI_MainLoop_Run()`](https://github.com/lc-soft/LCUI/blob/develop/src/main.c#L258) also has it.

**Comment by elfring** [comment]
* Which information do you try to express by the graphic above?
* Are you looking for further clarification around the terms "spurious wakeup" and "predicate"?

**Comment by lc-soft** [comment]
- pthread condition workflow.
- No, I am not  looking "spurious wakeup" and "predicate".

**Comment by lc-soft** [comment]
[This](https://github.com/lc-soft/LCUI/commit/9b8bc24e24f5bb2c062cc878ad08bc874a09a5aa#diff-9708724a55cd511ceebda2d4b3a7dabcR126) is correct? I added condition judgment.

**Comment by elfring** [comment]
It seems that [the mentioned source code adjustment is still incomplete](https://github.com/lc-soft/LCUI/commit/9b8bc24e24f5bb2c062cc878ad08bc874a09a5aa#diff-9708724a55cd511ceebda2d4b3a7dabcL105 "Update candidate: FrameControl_Remain()"), isn't it?

**Comment by elfring** [comment]
The implementation of the function "Win32Surface_New" is [another update candidate](https://github.com/lc-soft/LCUI/blob/6242456c4edf95a7655675c3fc6719bf39745b9e/src/output/win32_surface.c#L253 "More checks in Win32Surface_New()?"), isn't it?

**Comment by lc-soft** [comment]
@elfring 
`src/output/win32_surface.c` is old version, it will be delete, new version is `src/platform/windows/windows_display.c`.

**Comment by elfring** [comment]
I am curious on [how a final fix could look like](https://github.com/lc-soft/LCUI/commit/9b8bc24e24f5bb2c062cc878ad08bc874a09a5aa#diff-9708724a55cd511ceebda2d4b3a7dabcL123 "Update candidate: FrameControl_Remain()") for the discussed source code.

**Comment by lc-soft** [comment]
check [here](https://github.com/lc-soft/LCUI/blob/develop/src/util/framectrl.c#L118)

**Comment by elfring** [comment]
It seems that [the recent update](https://github.com/lc-soft/LCUI/blob/2b7c31c372199b9f7cb244f9097a772989b9bcef/src/util/framectrl.c#L99 "Is FrameControl_Remain() fixed?") makes the affected function usable.
