### ISSUE TITLE
x11 window title encoding bug

### ISSUE THREAD

**Issue by lc-soft** [lc-soft/LCUI#55]
![2016-10-01 20-13-12](https://cloud.githubusercontent.com/assets/1730073/19014041/008e6db0-8815-11e6-91f6-811078adcb4e.png)

**Comment by odknt** [comment]
This is probably not bug of LCUI. Try add code below to `main()`.

```c
#include <locale.h>

...

setlocale( LC_ALL, "" );

...
```
