### ISSUE TITLE
[render] box shadow bug

### ISSUE THREAD

**Issue by lc-soft** [lc-soft/LCUI#81]
**Screenshots and GIFs**

![shadow-bug](https://cloud.githubusercontent.com/assets/1730073/25071353/2507f932-22e7-11e7-8aca-a37301fda109.gif)

**Comment by sgf** [comment]
textedit can't select text ?

**Comment by mrwert** [comment]
@sgf 
Not yet...

**Comment by sgf** [comment]
@mrwert
thanks reply

**Comment by lc-soft** [comment]
Done.
