### ISSUE TITLE
[textedit] caret positioning and render problems

### ISSUE THREAD

**Issue by lc-soft** [lc-soft/LCUI#82]
**Screenshots and GIFs**
![textedit-bug](https://cloud.githubusercontent.com/assets/1730073/25071371/a457c5be-22e7-11e7-8d4a-fb29955d3884.gif)

**Comment by mrwert** [comment]
I did not know how to describe these problems, next time i will use the format gif.

**Comment by lc-soft** [comment]
Fixed.

**Before:**
![textedit-bug](https://cloud.githubusercontent.com/assets/1730073/25666999/b51799cc-3054-11e7-924c-a7b2f49dfc9d.gif)

**After:**
![textedit-bug-fixed](https://cloud.githubusercontent.com/assets/1730073/25667004/b9fc0928-3054-11e7-90f1-29e24a9dcf16.gif)
