### ISSUE TITLE
TextView_SetTextW works incorrectly

### ISSUE THREAD

**Issue by ReinForce-II** [lc-soft/LCUI#87]
When newtext is shorter than oldtext, part of oldtext will be visible.

**Reproduction Steps:**

1. <widget type="textview">11111111</widget>
2. TextView_SetTextW(foo, L"1");

![image](https://cloud.githubusercontent.com/assets/20750215/25310900/8c0be4ae-2823-11e7-9309-afb349dff197.png)
![image](https://cloud.githubusercontent.com/assets/20750215/25310901/91959ffa-2823-11e7-8196-fe6fb2f080f3.png)

**Comment by lc-soft** [comment]
**Before:**
![qq 20170501202857](https://cloud.githubusercontent.com/assets/1730073/25581869/d43f1f08-2ebc-11e7-83da-94efacf18266.png)


**After:**
![test-textview](https://cloud.githubusercontent.com/assets/1730073/25581871/d975968c-2ebc-11e7-8d3b-470720a8c6de.gif)
